CameraRGBBaseOptions: &CameraRGBBaseOptions
  "image_size_x": "640"
  "image_size_y": "360"
  "sensor_tick": "0.083333"
  "fstop": "1.8"
  "shutter_speed": "30.0"

RadarBaseOptions: &RadarBaseOptions
  'horizontal_fov': '80'
  'vertical_fov': '30'
  'points_per_second': '1500'
  'range': '250'
  'sensor_tick': '0.076923'

sensors:
  # 2Cam (월드 고정) + 1 Lidar(중심, 월드 고정)
  -
    name: "CAM_FIXED_1"
    bp_name: 'sensor.camera.rgb'
    attach_to: 'world'
    location:
      x: -97.330
      y: 7.528
      z: 7.0
    rotation:
      yaw: 122.57
      pitch: -20.0
      roll: 0
    options:
      <<: *CameraRGBBaseOptions
      "fov": "90"
      "image_size_x": "640"
      "image_size_y": "360"
      "sensor_tick": "0.1"
  -
    name: "CAM_FIXED_2"
    bp_name: 'sensor.camera.rgb'
    attach_to: 'world'
    location:
      x: -116.797
      y: 37.642
      z: 7.0
    rotation:
      yaw: -57.43
      pitch: -20.0
      roll: 0
    options:
      <<: *CameraRGBBaseOptions
      "fov": "90"
      "image_size_x": "640"
      "image_size_y": "360"
      "sensor_tick": "0.1"
  -
    name: "LIDAR_CENTER"
    bp_name: 'sensor.lidar.ray_cast'
    attach_to: 'world'
    location:
      x: -107.0635
      y: 22.585
      z: 7.0
    rotation:
      yaw: 0
      pitch: 0
      roll: 0
    options:
      'channels': '32'
      'points_per_second': '600000'
      'range': '80'
      'upper_fov': '10'
      'lower_fov': '-30'
      'horizontal_fov': '360'
      'sensor_tick': '0.1'
      'rotation_frequency': '10'
  # -
  #   name: "viz"
  #   bp_name: 'sensor.camera.rgb'
  #   location: 
  #     x: 0
  #     y: 0
  #     z: 2
  #   rotation:
  #     yaw: 0
  #     pitch: 0
  #     roll: 0
  #   options: 
  #       <<: *CameraRGBBaseOptions
  #       "fov": "70"
